title: "42 Docs"
description: "Find code examples, optimization tricks, and much more."

search_enabled: true
heading_anchors: true
color_scheme: dark
ga_tracking: UA-158921873-1

# Aux links for the upper right navigation
aux_links:
  "Github":
    - "//github.com/harm-smits/42docs"
  "Connect with me on LinkedIn":
    - "//www.linkedin.com/in/harmsmits/"

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
